version: '3'
services:
  client:
    build:
      context : ./Client
      dockerfile: Dockerfile
    expose:
      - 3001 #Socket IO Port
    ports:
      - "4200:4200"
    volumes:
      - "./Client/src:/root/src"
    command : npm start
    tty: true
  server :
    build:
      context: ./Server
      dockerfile: Dockerfile
    expose:
      - 3001 #Socket IO Port
    ports:
      - "3001:3001"
      - "3000:3000"
    command : npm start
    volumes: 
      - "./Server/src:/Server/src"
      - "./uploads:/Server/uploads"
    depends_on: 
      - mongo
    tty: true
  mongo :
    image: mongo
    volumes: 
      - "./data:/data/db"
    ports:
      - "27017:27017"
